<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>297872a0-8141-4095-a89b-8051914c2a65</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OllamaSharp" Version="5.4.8" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DataIngestion" Version="10.0.0-preview.1.25560.10" />
    <PackageReference Include="Microsoft.Extensions.DataIngestion.Markdig" Version="10.0.0-preview.1.25560.10" />
    <PackageReference Include="PdfPig" Version="0.1.11" />
    <PackageReference Include="Microsoft.ML.Tokenizers.Data.Cl100kBase" Version="2.0.0-preview.25503.2" />
    <PackageReference Include="Microsoft.ML.Tokenizers.Data.O200kBase" Version="2.0.0-preview.25503.2" />
    <PackageReference Include="System.Linq.Async" Version="6.0.3" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.SqliteVec" Version="1.67.1-preview" />
  </ItemGroup>

</Project>
